version: "3"

networks:
  study_projects:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: ./Docker/api/Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    networks:
      - study_projects
    depends_on:
      - mysql  

  mysql:
    build:
      context: ./Docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_consumer_microsservice
    ports:
      - "3004:3306"
    volumes:
      - db-data-consumer-microsservice:/var/lib/mysql     
    networks:
      - study_projects

volumes:
  db-data-consumer-microsservice:         